version: "3"

services:
  pvs_surl:
    build:
      context: .
    ports:
      - 5000:5000
  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=TRUE
    ports:
      - 0.0.0.0:3305:3306

